-- DEALAUTO follow-up §F2 — LESSOR and SELLER are not the same role, and the
-- lessee's own paperwork is not part of this mechanism at all.
--
-- Owner, 2026-08-22, ruling on the report's F2:
--   "lessor/seller are not handled the same. the seller doesnt retain authority
--    to release liability or grant vet auth. [the buyer] inherits that upon
--    signature on the BOS. so the docs invert for a BOS vs a lease. Lessee
--    paperwork is handled separately and doesnt gate signing nor required after
--    signing."
--
-- Two distinct corrections.
--
-- 1. THE HORSE DOCUMENTS FOLLOW AUTHORITY, AND AUTHORITY MOVES ON A SALE.
--    A lease does not transfer ownership: the LESSOR is still the owner the
--    morning after, so the emergency veterinary authorization and the care
--    liability release stay with them. A bill of sale DOES transfer it: the
--    moment it executes the SELLER has no authority to authorize veterinary
--    treatment or release anyone from anything, and the BUYER has all of it.
--    Same two documents, other end of the table.
--
--    Today the sale branch of apply_contract_execution_effects generates
--    NEITHER — `ensure_horse_documents` is called only in the lease branch. So
--    every sale FHE has ever written ends with a new owner and no vet
--    authorization and no care release on file. Fixed below, called AFTER the
--    ownership transfer so the generator's own "address it to the owner of
--    record" rule resolves to the buyer without being told.
--
-- 2. THE LESSEE OWES NOTHING BY VIRTUE OF BEING THE LESSEE.
--    `contract_role_documents` asked the LESSEE for COMPANY_POLICIES +
--    FACILITY_RULES — which is the onboarding wall, already collected by the
--    onboarding flow, from every client, before any of this. The report's F2
--    measured the consequence: that bundle is satisfied 100% of the time and
--    generates nothing, forever. It is duplication, not a requirement. Retired,
--    not deleted.

-- ── retire, never delete (standing rule) ───────────────────────────────────
ALTER TABLE public.contract_role_documents
  ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS retired_reason text;

UPDATE public.contract_role_documents
   SET active = false,
       retired_reason = 'DEALAUTO 2026-08-22 (owner): lessee paperwork is handled '
                     || 'separately by onboarding — it does not gate signing and is not '
                     || 'owed again after signing. These two rows duplicated the '
                     || 'onboarding wall exactly, so the LESSEE bundle was satisfied on '
                     || 'every contract and generated nothing.'
 WHERE doc_role = 'LESSEE';

-- ── the horse documents, stated on the role that actually holds them ───────
-- They are GENERATED by ensure_horse_documents, not by the role-bundle
-- generator — `owned_by` below says so, and the generator skips anything it
-- does not own. These rows exist so the requirements surface tells the whole
-- truth about a role instead of showing a gap where a working mechanism sits.
INSERT INTO public.contract_role_documents (org_id, doc_role, template_key)
SELECT o.id, r.doc_role, r.template_key
  FROM organizations o
  CROSS JOIN (VALUES
    -- a lease leaves ownership where it was: the lessor keeps the authority
    ('LESSOR', 'HORSE_EMERGENCY_VET'),
    ('LESSOR', 'RELEASE_HORSE_CARE'),
    -- a sale moves it: the buyer inherits both on signature
    ('BUYER',  'HORSE_EMERGENCY_VET'),
    ('BUYER',  'RELEASE_HORSE_CARE')
    -- and deliberately NOT the seller: after the bill of sale they hold nothing
    -- to authorize with and nothing to release
  ) AS r(doc_role, template_key)
 WHERE EXISTS (SELECT 1 FROM contract_role_documents c WHERE c.org_id = o.id)
ON CONFLICT (org_id, doc_role, template_key) DO NOTHING;

-- ── the requirements read: honour `active`, and name the owner of the horse
--    documents on a SALE as well as on a lease ────────────────────────────────
-- The `owned_by` marker is what stops ensure_contract_role_documents generating
-- a second, differently-shaped copy of a document ensure_horse_documents
-- already owns. It was gated on `v_is_lease`, so on a sale the four rows above
-- would have read 'unassigned' and been generated twice. Keyed on the template
-- now, which is the thing that is actually true.
CREATE OR REPLACE FUNCTION public.contract_role_document_requirements(p_document_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_org      uuid;
  v_contract uuid;
  v_key      text;
  v_rows     jsonb;
BEGIN
  SELECT d.org_id, d.contract_id, ct.template_key
    INTO v_org, v_contract, v_key
    FROM documents d
    LEFT JOIN contract_templates ct ON ct.id = d.template_id
   WHERE d.id = p_document_id AND d.deleted_at IS NULL;
  IF v_org IS NULL THEN RAISE EXCEPTION 'unknown document: %', p_document_id; END IF;

  -- Readable by staff, and by anyone who is themselves a party to this contract:
  -- a lessee is entitled to see what their own role owes.
  IF NOT (coalesce(has_staff_access(), false)
          OR EXISTS (SELECT 1 FROM document_parties dp
                      WHERE dp.document_id = p_document_id
                        AND dp.contact_id = current_contact_id())) THEN
    RAISE EXCEPTION 'not a party to this contract';
  END IF;

  SELECT coalesce(jsonb_agg(x ORDER BY x->>'party_role', x->>'template_key'), '[]'::jsonb)
    INTO v_rows
  FROM (
    SELECT jsonb_build_object(
             'contact_id',   dp.contact_id,
             'party_role',   dp.party_role,
             'party_name',   nullif(btrim(coalesce(c.first_name,'') || ' ' || coalesce(c.last_name,'')), ''),
             'party_email',  c.email,
             'template_key', crd.template_key,
             'title',        coalesce(t.title, crd.template_key),
             -- SATISFIED = an executed document of this template already on file
             -- for this party. Deliberately NOT contract-scoped: signing the
             -- Company Policies twice is not an obligation, it is a nuisance.
             'satisfied',    sat.document_id IS NOT NULL,
             'satisfied_document_id', sat.document_id,
             -- Anything of this template already sitting on THIS contract,
             -- whoever it is addressed to — the disagreement described above is
             -- visible rather than assumed away.
             'on_this_contract_document_id', onc.document_id,
             'on_this_contract_addressed_to', onc.contact_id,
             -- Who creates it, when it does not exist yet. DEALAUTO 2026-08-22:
             -- keyed on the TEMPLATE, not on lease-vs-sale. ensure_horse_documents
             -- owns these two on both kinds — on a lease it addresses them to the
             -- lessor, who stays the owner; on a sale to the buyer, who has just
             -- become one. Gated on `v_is_lease` it read 'unassigned' for a sale,
             -- and the role-bundle generator would have made a second copy.
             'owned_by',     CASE
               WHEN crd.template_key IN ('HORSE_EMERGENCY_VET','RELEASE_HORSE_CARE')
                 THEN 'ensure_horse_documents@execution'
               ELSE 'unassigned' END
           ) AS x
      FROM document_parties dp
      JOIN contacts c ON c.id = dp.contact_id
      JOIN contract_role_documents crd
        ON crd.org_id = v_org AND crd.doc_role = dp.party_role AND crd.active
      LEFT JOIN contract_templates t ON t.template_key = crd.template_key
      LEFT JOIN LATERAL (
        SELECT d2.id AS document_id FROM documents d2
         JOIN contract_templates t2 ON t2.id = d2.template_id
        WHERE d2.contact_id = dp.contact_id AND t2.template_key = crd.template_key
          AND d2.status = 'EXECUTED' AND d2.deleted_at IS NULL
        ORDER BY d2.generated_at DESC NULLS LAST LIMIT 1) sat ON true
      LEFT JOIN LATERAL (
        SELECT d3.id AS document_id, d3.contact_id FROM documents d3
         JOIN contract_templates t3 ON t3.id = d3.template_id
        WHERE t3.template_key = crd.template_key AND d3.deleted_at IS NULL
          AND (d3.contract_id IS NOT DISTINCT FROM v_contract AND v_contract IS NOT NULL)
        ORDER BY d3.generated_at DESC NULLS LAST LIMIT 1) onc ON true
     WHERE dp.document_id = p_document_id
       AND dp.party_role IN ('BUYER','LESSEE','LESSOR','SELLER')
       -- ⚠️ NEVER THE COMPANY. Wired literally, the seed table asks the LESSOR to
       -- sign Company Policies and a visitor liability release — and on every
       -- lease FHE writes, the LESSOR *is* French Heritage Equestrian.
       AND NOT coalesce(c.is_company, false)
  ) s;

  RETURN jsonb_build_object(
    'document_id', p_document_id,
    'contract_id', v_contract,
    'template_key', v_key,
    'requirements', v_rows);
END;
$function$;
