-- EMAILEXTRACT — seed the 19 extracted email templates (TASK-EMAILEXTRACT).
--
-- GENERATED by scripts/emailextract/gen-seed.mjs from scripts/emailextract/bodies.mjs.
-- Do not hand-edit: re-run the generator, or (once the Templates > Emails editor
-- exists) change the wording through the editor, which is the entire point of this
-- task. This file is the ONE-TIME lift out of TypeScript, not the ongoing home of
-- the words.
--
-- Every body here is proven byte-identical to what api/ produced on origin/main —
-- 220 checks in scripts/emailextract/diff.mjs, covering each optional branch of
-- each email (guardian vs signer, note vs no note, footer vs no footer, named vs
-- nameless recipient, single vs plural).
--
-- ON RE-RUN: content columns are NOT overwritten. An owner edit made through the
-- editor must survive a replay of this migration, so ON CONFLICT touches only the
-- documentation columns. Re-seeding wording is a deliberate act, not a side effect.

INSERT INTO public.email_templates
  (email_key, title, description, category, subject, body,
   from_address_rule, reply_to_rule, recipient_note, transactional)
VALUES
  ($emailextract$INVITATION$emailextract$,
   $emailextract$Account invitation$emailextract$,
   $emailextract$The activation link that turns an invited contact into an account holder. One template, two voices: the first send welcomes, the resend says "this is the same link you already have" so a mailbox can be triaged on the subject line.$emailextract$,
   $emailextract$INVITATION$emailextract$,
   $emailextract${{#if MSG.IS_RESEND}}Here's your invitation link again — {{ORG.BRAND_NAME}}{{else}}Your invitation to {{ORG.BRAND_NAME}}{{/if}}$emailextract$,
   $emailextract$
      {{#if MSG.IS_RESEND}}<p>Here's that link again — this is the <strong>same invitation</strong> we sent you
       before, not a new one. If you still have the first email, either link works.</p>{{else}}<p>Welcome — we're so glad to have you.</p>{{/if}}
      {{#if MSG.OFFERING_LABEL}}<p>Your {{MSG.OFFERING_LABEL}} is ready — create your account to sign your documents and get started.</p>{{/if}}
      {{#if MSG.CHECKLIST}}<p>When you click the link, here's what we'll ask you to do:</p><ul style="padding-left:18px">{{#each MSG.CHECKLIST}}<li style="margin:4px 0"><strong>{{.TITLE}}</strong> — {{.ACTION}}</li>{{/each}}</ul><p style="color:#666;font-size:13px">This same checklist will be on your dashboard, ticking itself off as you go.</p>{{/if}}
      <p>Create your account here to join the community. You can sign up with Google
      or set a password — your choice on the next page:</p>
      <p><a href="{{MSG.LINK}}">{{MSG.LINK}}</a></p>
      <p>{{#if MSG.EXPIRES_ON}}This link is valid until <strong>{{MSG.EXPIRES_ON}}</strong>. If it expires, just reach out and we'll send a fresh one.{{else}}This link expires soon. If it does, just reach out and we'll send a fresh one.{{/if}}</p>
      <hr/><pre style="font-family:inherit">{{ORG.FOOTER}}</pre>$emailextract$,
   $emailextract$invite$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The invited address on the invitation row. Staff-initiated (admin-send-invitation), staff resend (admin-resend-invitation) and the invitee's own "send it again" (invitation-resend-request) all reach this one template.$emailextract$,
   true),

  ($emailextract$CONTRACT_INVITE$emailextract$,
   $emailextract$Contract ready to sign$emailextract$,
   $emailextract$Sent to a contract counterparty when a document is prepared for them. The list of what they will be asked to do is built from that party's own document controls, so the email never promises an action the controls do not allow.$emailextract$,
   $emailextract$CONTRACT$emailextract$,
   $emailextract$A contract is ready for you — {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>Hello,</p><p><strong>{{#if DOC.HAS_TITLE}}{{DOC.TITLE}}{{else}}A contract{{/if}}</strong> has been prepared for you.</p><p><a href="{{MSG.LINK}}">Open the contract</a> — sign in with Google if this is a Gmail address, or set a password with this email. You'll land directly on the contract to {{#if DOC.PARTY_NEEDS_INFO}}add your information, {{/if}}{{#if DOC.PARTY_CAN_EDIT_DEAL}}review and edit the terms{{else}}{{#if DOC.PARTY_CAN_SUGGEST}}review and suggest changes{{else}}review the terms{{/if}}{{/if}}, and sign.</p><p style="color:#666;font-size:12px">This link is personal to {{MSG.RECIPIENT_EMAIL}} and expires in 14 days.<br/>{{MSG.LINK}}</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The counterparty contact on the named party role, at the address on their contact record (or one passed by staff). Never sent to someone who has already signed.$emailextract$,
   true),

  ($emailextract$CONTRACT_VOIDED$emailextract$,
   $emailextract$Contract voided by the other party$emailextract$,
   $emailextract$The email half of a void. The in-app notification is written by the database; this carries the same note plus the keep-or-remove choice, and says plainly that removing it only affects the reader's own documents page.$emailextract$,
   $emailextract$CONTRACT$emailextract$,
   $emailextract${{#if PARTY.FULL_NAME}}{{PARTY.FULL_NAME}}{{else}}The other party{{/if}} voided {{#if DOC.HAS_TITLE}}{{DOC.TITLE}}{{else}}your contract{{/if}}$emailextract$,
   $emailextract$<p>Hello,</p><p><strong>{{#if PARTY.FULL_NAME_HTML}}{{PARTY.FULL_NAME_HTML}}{{else}}The other party{{/if}}</strong> voided <strong>{{#if DOC.HAS_TITLE}}{{DOC.TITLE_HTML}}{{else}}your contract{{/if}}</strong>. It is no longer going ahead.</p>{{#if MSG.NOTE_HTML}}<p>They left this note:</p><blockquote style="margin:0 0 0 12px;padding-left:12px;border-left:3px solid #ddd;color:#444">{{MSG.NOTE_HTML}}</blockquote>{{else}}<p>No reason was given.</p>{{/if}}<p><a href="{{MSG.LINK}}">Open the contract</a> to keep a copy on your documents page, or remove it from your view.</p><p style="color:#666;font-size:12px">Removing it only affects your own documents page — the record is retained.<br/>{{MSG.LINK}}</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Every other party on the document who has an email address on file.$emailextract$,
   true),

  ($emailextract$CONTRACT_CHANGE_REQUESTS$emailextract$,
   $emailextract$Change requests submitted for review$emailextract$,
   $emailextract$Lists the five highest-impact change requests a party submitted. The ranking is the database's (change_request_impact_rank) — money, then liability, then term, and so on — so the email and the app agree on what matters most.$emailextract$,
   $emailextract$CONTRACT$emailextract$,
   $emailextract${{#if PARTY.FULL_NAME}}{{PARTY.FULL_NAME}}{{else}}The other party{{/if}} requested changes to {{#if DOC.HAS_TITLE}}{{DOC.TITLE}}{{else}}your contract{{/if}}$emailextract$,
   $emailextract$<p>Hello,</p><p><strong>{{#if PARTY.FULL_NAME_HTML}}{{PARTY.FULL_NAME_HTML}}{{else}}The other party{{/if}}</strong> submitted change requests on <strong>{{#if DOC.HAS_TITLE}}{{DOC.TITLE_HTML}}{{else}}your contract{{/if}}</strong> for your review.</p><p>The most significant {{#if MSG.IS_SINGLE}}one is{{else}}{{MSG.COUNT}} are{{/if}}:</p><ol>{{#each MSG.ITEMS}}<li style="margin-bottom:8px"><strong>#{{.NUMBER}} — {{#if .HAS_SECTION}}{{.WHERE_HTML}}{{else}}The whole document{{/if}}</strong><br/>{{.BODY_HTML}}</li>{{/each}}</ol><p><a href="{{MSG.LINK}}">Open the contract</a> to reply to each request and agree or discuss.</p><p style="color:#666;font-size:12px">The contract cannot be locked for signing until these are resolved.<br/>{{MSG.LINK}}</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Every other party on the document who has an email address on file.$emailextract$,
   true),

  ($emailextract$CONTRACT_WORKING_COPY$emailextract$,
   $emailextract$Working copy of a contract$emailextract$,
   $emailextract$A party asks for the contract as it stands right now, unexecuted, so an adviser can read it. Unselected options and empty fields are included on purpose and the email says so, because a working copy that looked finished would be worse than none.$emailextract$,
   $emailextract$CONTRACT$emailextract$,
   $emailextract$Working copy — {{#if DOC.HAS_TITLE}}{{DOC.TITLE}}{{else}}Contract{{/if}}$emailextract$,
   $emailextract$<p>Attached is the current working copy of <strong>{{#if DOC.HAS_TITLE}}{{DOC.TITLE}}{{else}}this contract{{/if}}</strong>{{#if DOC.DISPLAY_CODE}} ({{DOC.DISPLAY_CODE}}){{/if}}.</p><p>It is <strong>not executed</strong> and reflects the contract as of {{MSG.GENERATED_AT}}. Unselected options and empty fields are included on purpose, so anyone advising you can see what is still open.</p>$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The requesting party, at their contact address (falling back to their account's).$emailextract$,
   true),

  ($emailextract$DOCUMENT_PARTY_COPY$emailextract$,
   $emailextract$Your signed document (single)$emailextract$,
   $emailextract$A signer's own copy of one executed document, with the PDF attached. Deliberately plain — no personalised greeting, matching the company copy's tone. Only the PDF filename is personalised. Carries a short reference code, never the full integrity hash.$emailextract$,
   $emailextract$DOCUMENT$emailextract$,
   $emailextract${{DOC.TITLE}} — signed and executed$emailextract$,
   $emailextract${{#if MSG.IS_GUARDIAN_COPY}}<p>Hi {{#if PARTY.GUARDIAN_FIRST_NAME}}{{PARTY.GUARDIAN_FIRST_NAME}}{{else}}there{{/if}},</p><p>The document <strong>{{DOC.TITLE}}</strong> for {{#if PARTY.FULL_NAME}}{{PARTY.FULL_NAME}}{{else}}the minor named on this document{{/if}} has been signed and executed. The PDF is attached.</p>{{else}}<p>Your document <strong>{{DOC.TITLE}}</strong> has been signed and executed. The PDF is attached.</p>{{/if}}<p style="font-size:16px;margin-top:16px"><strong>{{ORG.BRAND_NAME}}</strong>{{#if ORG.PHONE}}<br/><a href="tel:{{ORG.PHONE_TEL}}" style="color:inherit;text-decoration:none">{{ORG.PHONE}}</a>{{/if}}{{#if ORG.SITE_LINK}}<br/><a href="https://{{ORG.SITE_HOST}}" style="color:inherit">{{ORG.SITE_LINK}}</a>{{/if}}</p>{{#if DOC.REFERENCE_CODE}}<p style="color:#888;font-size:12px">Reference code: {{DOC.REFERENCE_CODE}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Each party on the executed document, once per document (a unique index makes a duplicate impossible). A minor's copy is addressed to their guardian; with no guardian email the send is skipped and staff are alerted.$emailextract$,
   true),

  ($emailextract$DOCUMENT_COMPANY_COPY$emailextract$,
   $emailextract$Company copy — one document executed$emailextract$,
   $emailextract$The org inbox copy of a single execution. Unlike the party copy it carries the FULL SHA-256 integrity hash and the unstripped body, because this is the file-of-record copy.$emailextract$,
   $emailextract$DOCUMENT$emailextract$,
   $emailextract${{DOC.TITLE}} — signed and executed ({{DOC.DISPLAY_CODE}})$emailextract$,
   $emailextract$<p>{{#if PARTY.SIGNERS}}{{PARTY.SIGNERS}}{{else}}A signer{{/if}} executed <strong>{{DOC.TITLE}}</strong>. The signed PDF is attached.</p>{{#if DOC.INTEGRITY_HASH}}<hr/><p style="color:#666;font-size:12px">Integrity hash (SHA-256): {{DOC.INTEGRITY_HASH}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The org public contact address, once per document, and only when at least one party copy actually sent. Skipped when that inbox was already a party recipient.$emailextract$,
   false),

  ($emailextract$DOCUMENT_SET_PARTY_COPY$emailextract$,
   $emailextract$Your signed documents (set)$emailextract$,
   $emailextract$One email with every document of a flow attached as its own PDF, instead of one email per document. This is what an onboarding signer receives after the participant flow.$emailextract$,
   $emailextract$DOCUMENT$emailextract$,
   $emailextract$Your signed documents — {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>{{#if PARTY.GREETING_NAME}}Hi {{PARTY.GREETING_NAME}},{{else}}Hello,{{/if}}</p>{{#if MSG.IS_GUARDIAN_COPY}}<p>The signed documents for {{#if PARTY.FULL_NAME}}{{PARTY.FULL_NAME}}{{else}}the minor named below{{/if}} are attached to this email:</p>{{else}}<p>Thank you. Your signed documents are attached to this email:</p>{{/if}}<ul>{{#each DOC.TITLES}}<li>{{.}}</li>{{/each}}</ul><p>Please keep these for your records.</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Each distinct signer across the whole set, once. Guardian-addressed for a minor. A staff "send me a copy" is targeted and logged as a mirror, not a party delivery.$emailextract$,
   true),

  ($emailextract$DOCUMENT_SET_COMPANY_COPY$emailextract$,
   $emailextract$Company copy — document set executed$emailextract$,
   $emailextract$The ops-inbox mirror of a completed set. Never fires for a staff-targeted re-send: that is not a new execution event and must not ping the inbox twice.$emailextract$,
   $emailextract$DOCUMENT$emailextract$,
   $emailextract$Signed document set{{#if PARTY.SIGNERS}} — {{PARTY.SIGNERS}}{{/if}}$emailextract$,
   $emailextract$<p>{{#if PARTY.SIGNERS}}{{PARTY.SIGNERS}}{{else}}A signer{{/if}} executed the following documents (attached):</p><ul>{{#each DOC.TITLES}}<li>{{.}}</li>{{/each}}</ul>$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The ops inbox (CONTACT.OPS_INBOX), falling back to the public contact address.$emailextract$,
   false),

  ($emailextract$DOCUMENT_WITHDRAWN$emailextract$,
   $emailextract$A document you were shown has been withdrawn$emailextract$,
   $emailextract$Sent before a non-executed document is hard-deleted, to anyone who was notified about it or had it delivered. They keep a PDF of the draft they reviewed even though the document itself is about to stop existing.$emailextract$,
   $emailextract$DOCUMENT$emailextract$,
   $emailextract${{DOC.TITLE}} was withdrawn — copy attached$emailextract$,
   $emailextract$<p>{{#if PARTY.GREETING_NAME}}Hi {{PARTY.GREETING_NAME}},{{else}}Hello,{{/if}}</p><p>The document <strong>{{DOC.TITLE}}</strong> that was shared with you has been withdrawn and removed. A copy is attached to this email for your records.</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Parties who have "seen" the document — an in-app notification linking to it, or a delivery row — and who have an email on file.$emailextract$,
   true),

  ($emailextract$EVALUATION_REPORT$emailextract$,
   $emailextract$Horse evaluation report$emailextract$,
   $emailextract$Delivers a completed evaluation report as a PDF. Three voices in one template: the buyer's own copy, a copy shared with someone else, and a guardian-addressed copy when the report belongs to a minor.$emailextract$,
   $emailextract$EVALUATION$emailextract$,
   $emailextract${{DOC.TITLE}}{{#if HORSE.LABEL}} — {{HORSE.LABEL}}{{/if}} — {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>{{#if PARTY.GREETING_NAME}}Hi {{PARTY.GREETING_NAME}},{{else}}Hello,{{/if}}</p>{{#if MSG.IS_GUARDIAN_COPY}}<p>A horse evaluation report{{#if HORSE.LABEL}} for {{HORSE.LABEL}}{{/if}} has been prepared for {{#if PARTY.FULL_NAME}}{{PARTY.FULL_NAME}}{{else}}the account holder{{/if}} and is attached to this email.</p>{{else}}{{#if MSG.IS_SHARE}}<p>A horse evaluation report has been shared with you{{#if HORSE.LABEL}} for {{HORSE.LABEL}}{{/if}}. It's attached to this email.</p>{{else}}<p>Your horse evaluation report{{#if HORSE.LABEL}} for {{HORSE.LABEL}}{{/if}} is attached to this email.</p>{{/if}}{{/if}}<p>Please keep it for your records.</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The report's buyer contact, an explicitly shared address, or the guardian of a minor buyer. A minor with no guardian email is refused, not redirected.$emailextract$,
   true),

  ($emailextract$EMAIL_CHANGE_VERIFY$emailextract$,
   $emailextract$Verify a new sign-in email$emailextract$,
   $emailextract$Sent to the NEW address when a member changes their sign-in email by password. The current email keeps working until they verify, and the email says so — that reassurance is the whole point of the message.$emailextract$,
   $emailextract$ACCOUNT$emailextract$,
   $emailextract$Verify your new email — {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>{{#if PARTY.GREETING_NAME}}Hi {{PARTY.GREETING_NAME}},{{else}}Hello,{{/if}}</p><p>You asked to change your sign-in email to <strong>{{MSG.NEW_EMAIL}}</strong>.</p><p><a href="{{MSG.LINK}}">Verify this address</a> and sign in with it plus the password you just set to finish the switch. Your current email keeps working until then.</p><p style="color:#666;font-size:12px">If the link doesn't open, check your spam folder or paste it into your browser:<br/>{{MSG.LINK}}</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The new address only. The Google path sends nothing at all — the linked identity is the proof there.$emailextract$,
   true),

  ($emailextract$ORDER_RECEIPT$emailextract$,
   $emailextract$Payment receipt$emailextract$,
   $emailextract$Confirms a payment after an order flips to confirmed, from either the Stripe webhook or the Zelle reconcile. Provable and single: every attempt is logged and a second send is refused once one has succeeded.$emailextract$,
   $emailextract$ORDER$emailextract$,
   $emailextract$Your receipt from {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>We received your payment{{#if TXN.AMOUNT}} of {{TXN.AMOUNT}}{{/if}}. Thank you.</p>
<hr/><pre style="font-family:inherit">{{ORG.FOOTER}}</pre>$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The buyer's account email.$emailextract$,
   true),

  ($emailextract$HOLD_EXPIRED$emailextract$,
   $emailextract$Booking hold expired$emailextract$,
   $emailextract$The 48-hour hold on a requested booking lapsed without payment. Deliberately warm and non-final — the closing line invites them to reply and get fresh dates rather than treating the lapse as a rejection.$emailextract$,
   $emailextract$BOOKING$emailextract$,
   $emailextract$Your hold has expired — {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>{{#if PARTY.GREETING_NAME}}Hi {{PARTY.GREETING_NAME}},{{else}}Hello,{{/if}}</p><p>The 48-hour hold on your requested booking has expired because payment wasn't completed in time.</p>{{#if MSG.ITEMS}}<ul>{{#each MSG.ITEMS}}<li>{{.}}</li>{{/each}}</ul>{{/if}}<p>No problem — just reply and we'll re-offer new dates with a fresh hold.</p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The requester on each lapsed hold, grouped so one person gets one email listing all of theirs.$emailextract$,
   true),

  ($emailextract$NOTIFICATION_DIGEST$emailextract$,
   $emailextract$Daily update digest$emailextract$,
   $emailextract$One daily email listing in-app notifications a member has not read. Nothing is included until it is 30 minutes old, so reading something in the app right now never produces an email about it.$emailextract$,
   $emailextract$DIGEST$emailextract$,
   $emailextract$You have {{MSG.COUNT}} {{#if MSG.IS_SINGLE}}update{{else}}updates{{/if}} at {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>Here's what's waiting for you at {{ORG.BRAND_NAME}}:</p><ul>{{#each MSG.ITEMS}}<li>{{.}}</li>{{/each}}</ul><p><a href="{{MSG.LINK}}">Open the app to catch up</a></p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Each member with unread, never-emailed notifications older than the grace window. At most ten items per person per run; the rest roll to the next.$emailextract$,
   false),

  ($emailextract$CALENDAR_UPDATE$emailextract$,
   $emailextract$Calendar update$emailextract$,
   $emailextract$Booking and lease reminders, sent on the hour rather than waiting for the daily digest. Only sends between 6am and 9pm Pacific; outside the window the in-app rows are still written.$emailextract$,
   $emailextract$DIGEST$emailextract$,
   $emailextract$Calendar update — {{ORG.BRAND_NAME}}$emailextract$,
   $emailextract$<p>Calendar update from {{ORG.BRAND_NAME}}:</p><ul>{{#each MSG.ITEMS}}<li>{{.}}</li>{{/each}}</ul><p><a href="{{MSG.LINK}}">Open your calendar</a></p>{{#if ORG.FOOTER}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER}}</p>{{/if}}$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$Each member with un-emailed booking_* or lease_* notifications.$emailextract$,
   false),

  ($emailextract$CALENDAR_OPS_DIGEST$emailextract$,
   $emailextract$Upcoming sessions (ops inbox)$emailextract$,
   $emailextract$One consolidated copy of the hour's booking reminders to the shared ops inbox, so the barn sees everything coming up without reading each rider's copy.$emailextract$,
   $emailextract$DIGEST$emailextract$,
   $emailextract$Upcoming sessions ({{MSG.COUNT}})$emailextract$,
   $emailextract$<p>Upcoming calendar items:</p><ul>{{#each MSG.ITEMS}}<li>{{.}}</li>{{/each}}</ul>$emailextract$,
   $emailextract$tenant$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The ops inbox only. One email per sweep, de-duplicated across members.$emailextract$,
   false),

  ($emailextract$REQUEST_RECEIVED$emailextract$,
   $emailextract$New website inquiry$emailextract$,
   $emailextract$The full submission from a public intake form, mailed to the barn immediately so the owners see what was actually written without opening the app. Replies go straight to the visitor.$emailextract$,
   $emailextract$INBOUND$emailextract$,
   $emailextract$New inquiry from {{#if MSG.SENDER_NAME}}{{MSG.SENDER_NAME}}{{else}}A visitor{{/if}}$emailextract$,
   $emailextract$<p><strong>{{#if MSG.SENDER_NAME_HTML}}{{MSG.SENDER_NAME_HTML}}{{else}}A visitor{{/if}}</strong> just submitted an inquiry on the website.</p><ul style="padding-left:18px"><li><strong>Email:</strong> {{REQ.EMAIL_HTML}}</li>{{#if REQ.PHONE_HTML}}<li><strong>Phone:</strong> {{REQ.PHONE_HTML}}</li>{{/if}}{{#if REQ.CONTACT_METHOD_HTML}}<li><strong>Prefers:</strong> {{REQ.CONTACT_METHOD_HTML}}</li>{{/if}}{{#if REQ.CATEGORY_HTML}}<li><strong>Interested in:</strong> {{REQ.CATEGORY_HTML}}</li>{{/if}}{{#if REQ.CHANNEL_HTML}}<li><strong>Via:</strong> {{REQ.CHANNEL_HTML}}</li>{{/if}}{{#if REQ.ENTRY_LOCATION_HTML}}<li><strong>From:</strong> {{REQ.ENTRY_LOCATION_HTML}}</li>{{/if}}{{#if REQ.SUBJECT_HTML}}<li><strong>Subject:</strong> {{REQ.SUBJECT_HTML}}</li>{{/if}}{{#if REQ.INTENT_HTML}}<li><strong>Intent:</strong> {{REQ.INTENT_HTML}}</li>{{/if}}<li><strong>Submitted:</strong> {{REQ.SUBMITTED_AT_HTML}}</li></ul>{{#if REQ.AVAILABILITY_HTML}}<p><strong>Availability:</strong> {{REQ.AVAILABILITY_HTML}}</p>{{/if}}{{#if REQ.DETAILS}}<ul style="padding-left:18px">{{#each REQ.DETAILS}}<li><strong>{{.LABEL}}:</strong> {{.VALUE}}</li>{{/each}}</ul>{{/if}}{{#if REQ.NOTES_HTML}}<p style="white-space:pre-line;border-left:3px solid #ddd;padding-left:12px;color:#333">{{REQ.NOTES_HTML}}</p>{{/if}}<p><a href="{{MSG.LINK}}">Open the Request Inbox</a> to reply.</p>{{#if ORG.FOOTER_HTML}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER_HTML}}</p>{{/if}}$emailextract$,
   $emailextract$tenant_or_recipient$emailextract$,
   $emailextract$submitter$emailextract$,
   $emailextract$The tenant's configured ops inbox only. Never an address taken from the submission — every field in this email is read back from the stored request row.$emailextract$,
   true),

  ($emailextract$SUPPORT_RECEIVED$emailextract$,
   $emailextract$New support request$emailextract$,
   $emailextract$A signed-in member asked for help from their account page. Fired by the database itself right after the request row lands, so the barn hears about it whether or not anyone is in the app.$emailextract$,
   $emailextract$INBOUND$emailextract$,
   $emailextract$New website inquiry — {{#if PARTY.FULL_NAME}}{{PARTY.FULL_NAME}}{{else}}A member{{/if}}$emailextract$,
   $emailextract$<p><strong>{{#if PARTY.FULL_NAME_HTML}}{{PARTY.FULL_NAME_HTML}}{{else}}A member{{/if}}</strong> just submitted a support request.</p>{{#if PARTY.EMAIL_HTML}}<ul style="padding-left:18px"><li><strong>Email:</strong> {{PARTY.EMAIL_HTML}}</li></ul>{{/if}}<p><strong>Subject:</strong> {{MSG.SUBJECT_HTML}}</p><p style="white-space:pre-line;border-left:3px solid #ddd;padding-left:12px;color:#333">{{MSG.BODY_HTML}}</p><p><a href="{{MSG.LINK}}">Open Support</a> to reply.</p>{{#if ORG.FOOTER_HTML}}<hr/><p style="color:#666;font-size:12px;white-space:pre-line">{{ORG.FOOTER_HTML}}</p>{{/if}}$emailextract$,
   $emailextract$tenant_or_recipient$emailextract$,
   $emailextract$none$emailextract$,
   $emailextract$The tenant's configured ops inbox only.$emailextract$,
   true)
ON CONFLICT (email_key) DO UPDATE SET
  title          = EXCLUDED.title,
  description    = EXCLUDED.description,
  category       = EXCLUDED.category,
  recipient_note = EXCLUDED.recipient_note;
