/*
  # FHE CRM — Token Dictionary Sync (owner template revision 2026-07-03)

  The owner replaced every contract body (supabase/contract_templates .md
  sources → regenerated 20260629100000_load_contract_bodies.sql). The revised bodies use
  tokens the GLOBAL dictionary (template_tokens WHERE template_id IS NULL) never
  carried. Per the dictionary's own rule — a field is added to the dictionary
  before it is used — this migration closes the gap. Descriptions come from
  docs/TOKEN_DICTIONARY.md (owner canon, 2026-07-03 revision).

  Shape rules (matching the 20260629040000 seed):
  - kind: SIG.* = 'signature', DOC.* = 'system', everything else 'field'.
    (No new SIG/DOC rows are needed: {{SIG.<ROLE>.NAME/DATE}} normalize onto the
    PARTY-scoped {{SIG.PARTY.*}} rows and {{DOC.EFFECTIVE_DATE}} already exists.)
  - party_scoped = true for tokens in the party namespaces (CLIENT here). The
    shared person field set (FULL_NAME / PRINTED_NAME / ADDRESS / PHONE / EMAIL /
    DOB) stays under the single PARTY placeholder — one dictionary row serves
    CLIENT / PARTICIPANT / SELLER / BUYER / LESSOR / LESSEE alike — so only the
    CLIENT-specific profile/attestation fields get literal CLIENT rows.
  - ORD.* / REQ.* are NON-party input namespaces (order instance / request
    inputs submitted with an order).
  - source_table/source_column are documentation metadata (text, not FKs); some
    name columns that arrive with later flows (Flow A request capture), exactly
    like the seed's 'intake' rows.

  Dictionary rows for concepts the revision REMOVED (e.g. ORG.LEGAL_IDENTITY,
  the FHE.* aliases) are deliberately left in place — global rows are harmless
  and per-template usage rows are regenerated by the loader.
*/

INSERT INTO template_tokens (namespace, field, token, kind, source_table, source_column, computed, required, party_scoped, notes) VALUES
  -- CLIENT namespace — profile autofill + attestations (owner canon: CLIENT.*
  -- autofills from the authenticated person's profile/contacts record) --------
  ('CLIENT','HORSE_CAPACITY',                  '{{CLIENT.HORSE_CAPACITY}}',                  'field', 'horse_parties', 'role',                             true,  false, true, 'Capacity as to the horse (owner, co-owner, lessee, authorized agent), resolved from horse_parties.role at signing. Equine services release, vet auth.'),
  ('CLIENT','EUTHANASIA_INITIALS',             '{{CLIENT.EUTHANASIA_INITIALS}}',             'field', NULL,            NULL,                               false, false, true, 'Initials acknowledging the euthanasia-approval clause. Vet auth; captured at the acknowledgment event.'),
  ('CLIENT','RIDING_EXPERIENCE_YEARS',         '{{CLIENT.RIDING_EXPERIENCE_YEARS}}',         'field', 'contacts',      'riding_experience_years',          false, false, true, 'Years of riding experience attested. Participant release, jumper addendum.'),
  ('CLIENT','JUMP_EXPERIENCE',                 '{{CLIENT.JUMP_EXPERIENCE}}',                 'field', 'contacts',      'jump_experience',                  false, false, true, 'Prior jumping experience and maximum height schooled. Participant release, jumper addendum.'),
  ('CLIENT','RIDING_BACKGROUND',               '{{CLIENT.RIDING_BACKGROUND}}',               'field', 'contacts',      'riding_background',                false, false, true, 'Prior instruction, showing, or competition experience. Participant release, jumper addendum.'),
  ('CLIENT','JUMP_LIMITATIONS',                '{{CLIENT.JUMP_LIMITATIONS}}',                'field', 'contacts',      'jump_limitations',                 false, false, true, 'Relevant injuries, physical limitations, or riding gaps. Jumper addendum.'),
  ('CLIENT','EMERGENCY_CONTACT_1_NAME',        '{{CLIENT.EMERGENCY_CONTACT_1_NAME}}',        'field', 'contacts',      'emergency_contact_1_name',         false, false, true, 'Primary emergency contact name. Medical auth, vet auth.'),
  ('CLIENT','EMERGENCY_CONTACT_1_RELATIONSHIP','{{CLIENT.EMERGENCY_CONTACT_1_RELATIONSHIP}}','field', 'contacts',      'emergency_contact_1_relationship', false, false, true, 'Primary emergency contact relationship. Medical auth, vet auth.'),
  ('CLIENT','EMERGENCY_CONTACT_1_PHONE',       '{{CLIENT.EMERGENCY_CONTACT_1_PHONE}}',       'field', 'contacts',      'emergency_contact_1_phone',        false, false, true, 'Primary emergency contact phone. Medical auth, vet auth.'),
  ('CLIENT','EMERGENCY_CONTACT_2_NAME',        '{{CLIENT.EMERGENCY_CONTACT_2_NAME}}',        'field', 'contacts',      'emergency_contact_2_name',         false, false, true, 'Secondary emergency contact name. Medical auth.'),
  ('CLIENT','EMERGENCY_CONTACT_2_RELATIONSHIP','{{CLIENT.EMERGENCY_CONTACT_2_RELATIONSHIP}}','field', 'contacts',      'emergency_contact_2_relationship', false, false, true, 'Secondary emergency contact relationship. Medical auth.'),
  ('CLIENT','EMERGENCY_CONTACT_2_PHONE',       '{{CLIENT.EMERGENCY_CONTACT_2_PHONE}}',       'field', 'contacts',      'emergency_contact_2_phone',        false, false, true, 'Secondary emergency contact phone. Medical auth.'),

  -- ORD namespace — the order instance (the generated document IS the order copy)
  ('ORD','UUID',              '{{ORD.UUID}}',              'field', 'documents',        'id',         true,  false, false, 'Unique identifier of the order copy; joins order, approval, payment memo, and receipt. Used in the five order forms (resolves to the document id).'),
  ('ORD','SERVICE_SELECTION', '{{ORD.SERVICE_SELECTION}}', 'field', 'client_purchases', 'tier_label', false, false, false, 'The specific service(s) selected from the offering list for this order. Lesson, training, and exercise order forms.'),

  -- REQ namespace — request inputs submitted with an order (Flow A public
  -- request form; merge blank until captured) ---------------------------------
  ('REQ','PREFERRED_SCHEDULE',  '{{REQ.PREFERRED_SCHEDULE}}',  'field', 'intake', 'preferred_schedule',  false, false, false, 'Client-submitted preferred dates and times for scheduling. All five order forms.'),
  ('REQ','LOCATION_PREFERENCE', '{{REQ.LOCATION_PREFERENCE}}', 'field', 'intake', 'location_preference', false, false, false, 'Requested service location where applicable. Lesson, horsemanship, training, exercise order forms.'),
  ('REQ','NOTES',               '{{REQ.NOTES}}',               'field', 'intake', 'notes',               false, false, false, 'Free-text notes submitted with the request. All five order forms.'),
  ('REQ','CONDITION_UPDATES',   '{{REQ.CONDITION_UPDATES}}',   'field', 'intake', 'condition_updates',   false, false, false, 'Client-reported horse condition changes since the last engagement. Training and exercise order forms.'),

  -- ENG namespace — engagement scope inputs (set per engagement at approval) ---
  ('ENG','SEARCH_OBJECTIVE',        '{{ENG.SEARCH_OBJECTIVE}}',        'field', 'intake', 'search_objective',        false, false, false, 'Search objective statement. Search retainer.'),
  ('ENG','BREED_PREFERENCE',        '{{ENG.BREED_PREFERENCE}}',        'field', 'intake', 'breed_preference',        false, false, false, 'Search parameter: breed preference. Search retainer.'),
  ('ENG','AGE_RANGE',               '{{ENG.AGE_RANGE}}',               'field', 'intake', 'age_range',               false, false, false, 'Search parameter: age range. Search retainer.'),
  ('ENG','HEIGHT_RANGE',            '{{ENG.HEIGHT_RANGE}}',            'field', 'intake', 'height_range',            false, false, false, 'Search parameter: height range. Search retainer.'),
  ('ENG','ADDITIONAL_REQUIREMENTS', '{{ENG.ADDITIONAL_REQUIREMENTS}}', 'field', 'intake', 'additional_requirements', false, false, false, 'Search parameter: additional requirements. Search retainer.'),
  ('ENG','EXPERIENCE_LEVEL',        '{{ENG.EXPERIENCE_LEVEL}}',        'field', 'intake', 'experience_level',        false, false, false, 'Rider experience level for suitability. Evaluation, search retainer.'),
  ('ENG','COMPETITION_GOALS',       '{{ENG.COMPETITION_GOALS}}',       'field', 'intake', 'competition_goals',       false, false, false, 'Competition goals. Evaluation.'),
  ('ENG','OTHER_CONSIDERATIONS',    '{{ENG.OTHER_CONSIDERATIONS}}',    'field', 'intake', 'other_considerations',    false, false, false, 'Other evaluation considerations. Evaluation.'),
  ('ENG','DISCLOSURES',             '{{ENG.DISCLOSURES}}',             'field', 'intake', 'disclosures',             false, false, false, 'Company conflict/relationship disclosures. Evaluation, search retainer.'),
  ('ENG','PROGRAM_SCOPE',           '{{ENG.PROGRAM_SCOPE}}',           'field', 'intake', 'program_scope',           false, false, false, 'Specific horsemanship program scope. Horsemanship order form.'),

  -- HORSE namespace — vet-auth structured fields + seller disclosure histories -
  ('HORSE','OWNER_NAME',              '{{HORSE.OWNER_NAME}}',              'field', 'horses',        'owner_name',              false, false, false, 'Owner or seller of a third-party horse being evaluated. Evaluation order form.'),
  ('HORSE','KNOWN_CONDITIONS',        '{{HORSE.KNOWN_CONDITIONS}}',        'field', 'horses',        'known_conditions',        false, false, false, 'Disclosed medical/behavioral conditions. Vet auth.'),
  ('HORSE','MEDICATION_NAME',         '{{HORSE.MEDICATION_NAME}}',         'field', 'horse_records', 'medication_name',         false, false, false, 'Authorized medication details (name), per-horse structured field. Vet auth.'),
  ('HORSE','MEDICATION_DOSAGE',       '{{HORSE.MEDICATION_DOSAGE}}',       'field', 'horse_records', 'medication_dosage',       false, false, false, 'Authorized medication details (dosage), per-horse structured field. Vet auth.'),
  ('HORSE','MEDICATION_INSTRUCTIONS', '{{HORSE.MEDICATION_INSTRUCTIONS}}', 'field', 'horse_records', 'medication_instructions', false, false, false, 'Authorized medication details (instructions), per-horse structured field. Vet auth.'),
  ('HORSE','MEDICATION_ADDITIONAL',   '{{HORSE.MEDICATION_ADDITIONAL}}',   'field', 'horse_records', 'medication_additional',   false, false, false, 'Authorized medication details (additional), per-horse structured field. Vet auth.'),
  ('HORSE','TRAINING_HISTORY',        '{{HORSE.TRAINING_HISTORY}}',        'field', 'horse_records', 'training_history',        false, false, false, 'Seller disclosure history: training. Purchase/sale.'),
  ('HORSE','COMPETITION_HISTORY',     '{{HORSE.COMPETITION_HISTORY}}',     'field', 'horse_records', 'competition_history',     false, false, false, 'Seller disclosure history: competition. Purchase/sale.'),
  ('HORSE','MEDICAL_HISTORY',         '{{HORSE.MEDICAL_HISTORY}}',         'field', 'horse_records', 'medical_history',         false, false, false, 'Seller disclosure history: medical. Purchase/sale.'),
  ('HORSE','BEHAVIORAL_HISTORY',      '{{HORSE.BEHAVIORAL_HISTORY}}',      'field', 'horse_records', 'behavioral_history',      false, false, false, 'Seller disclosure history: behavioral. Purchase/sale.'),
  ('HORSE','MEDICATION_HISTORY',      '{{HORSE.MEDICATION_HISTORY}}',      'field', 'horse_records', 'medication_history',      false, false, false, 'Seller disclosure history: medication. Purchase/sale.'),

  -- TXN namespace — fees and transaction terms of the revised instruments ------
  ('TXN','JUMPER_TRAINING_FEE',          '{{TXN.JUMPER_TRAINING_FEE}}',          'field', 'transactions', 'jumper_training_fee',          false, false, false, 'Jumper training rate. Lesson order form (conditional JUMPER_TRAINING_FEE section).'),
  ('TXN','PACKAGE_FEE',                  '{{TXN.PACKAGE_FEE}}',                  'field', 'transactions', 'service_fee',                  false, false, false, 'Multi-lesson package price. Lesson order form.'),
  ('TXN','SESSION_FEE',                  '{{TXN.SESSION_FEE}}',                  'field', 'transactions', 'session_fee',                  false, false, false, 'Per-session fee for horse training or exercise. Training and exercise order forms.'),
  ('TXN','MONTHLY_FEE',                  '{{TXN.MONTHLY_FEE}}',                  'field', 'transactions', 'monthly_fee',                  false, false, false, 'Monthly program fee. Training and exercise order forms.'),
  ('TXN','OTHER_FEES',                   '{{TXN.OTHER_FEES}}',                   'field', 'transactions', 'other_fees',                   false, false, false, 'Additional itemized fees. Training and exercise order forms.'),
  ('TXN','ADDITIONAL_SERVICES',          '{{TXN.ADDITIONAL_SERVICES}}',          'field', 'transactions', 'additional_services',          false, false, false, 'Additional evaluation services and pricing. Evaluation order form.'),
  ('TXN','PAYMENT_METHOD',               '{{TXN.PAYMENT_METHOD}}',               'field', 'transactions', 'payment_method',               false, false, false, 'Method of payment for a sale. Purchase/sale, transfer.'),
  ('TXN','TRANSFER_CONDITION',           '{{TXN.TRANSFER_CONDITION}}',           'field', 'transactions', 'transfer_condition',           false, false, false, 'Event upon which ownership transfers. Purchase/sale, transfer.'),
  ('TXN','TRANSFER_DATE',                '{{TXN.TRANSFER_DATE}}',                'field', 'transactions', 'transfer_date',                false, false, false, 'Ownership transfer date. Transfer.'),
  ('TXN','TRANSPORT_RESPONSIBILITY',     '{{TXN.TRANSPORT_RESPONSIBILITY}}',     'field', 'transactions', 'transport_responsibility',     false, false, false, 'Party responsible for transport. Purchase/sale, transfer.'),
  ('TXN','RISK_TRANSFER',                '{{TXN.RISK_TRANSFER}}',                'field', 'transactions', 'risk_transfer',                false, false, false, 'When risk of loss transfers. Purchase/sale, transfer.'),
  ('TXN','ADDITIONAL_DISCLOSURES',       '{{TXN.ADDITIONAL_DISCLOSURES}}',       'field', 'transactions', 'additional_disclosures',       false, false, false, 'Seller disclosures beyond the standard set. Purchase/sale, transfer.'),
  ('TXN','PPE_STATUS',                   '{{TXN.PPE_STATUS}}',                   'field', 'transactions', 'ppe_status',                   false, false, false, 'Pre-purchase exam completed or declined. Purchase/sale, transfer.'),
  ('TXN','PPE_DATE',                     '{{TXN.PPE_DATE}}',                     'field', 'transactions', 'ppe_date',                     false, false, false, 'Pre-purchase exam date. Purchase/sale, transfer.'),
  ('TXN','TRIAL_TERMS',                  '{{TXN.TRIAL_TERMS}}',                  'field', 'transactions', 'trial_terms',                  false, false, false, 'Trial period terms. Purchase/sale, transfer.'),
  ('TXN','TRIAL_RISK_PARTY',             '{{TXN.TRIAL_RISK_PARTY}}',             'field', 'transactions', 'trial_risk_party',             false, false, false, 'Party bearing risk during trial. Purchase/sale.'),
  ('TXN','TRIAL_CARE_PARTY',             '{{TXN.TRIAL_CARE_PARTY}}',             'field', 'transactions', 'trial_care_party',             false, false, false, 'Party responsible for care during trial. Purchase/sale, transfer.'),
  ('TXN','WARRANTIES',                   '{{TXN.WARRANTIES}}',                   'field', 'transactions', 'warranties',                   false, false, false, 'Express seller warranties. Purchase/sale.'),
  ('TXN','DOCUMENTS_TRANSFERRED',        '{{TXN.DOCUMENTS_TRANSFERRED}}',        'field', 'transactions', 'documents_transferred',        false, false, false, 'Registration/health/competition documents conveyed. Purchase/sale, transfer.'),
  ('TXN','EQUIPMENT_INCLUDED',           '{{TXN.EQUIPMENT_INCLUDED}}',           'field', 'transactions', 'equipment_included',           false, false, false, 'Equipment conveyed. Purchase/sale, transfer.'),
  ('TXN','EQUIPMENT_EXCLUDED',           '{{TXN.EQUIPMENT_EXCLUDED}}',           'field', 'transactions', 'equipment_excluded',           false, false, false, 'Equipment excluded. Purchase/sale, transfer.'),
  ('TXN','DEFAULT_TERMS',                '{{TXN.DEFAULT_TERMS}}',                'field', 'transactions', 'default_terms',                false, false, false, 'Default remedies. Purchase/sale, transfer.'),
  ('TXN','LEASE_TYPE',                   '{{TXN.LEASE_TYPE}}',                   'field', 'transactions', 'lease_type',                   false, false, false, 'Full or partial lease. Lease.'),
  ('TXN','LEASE_START',                  '{{TXN.LEASE_START}}',                  'field', 'transactions', 'lease_start',                  false, false, false, 'Lease start date. Lease.'),
  ('TXN','LEASE_END',                    '{{TXN.LEASE_END}}',                    'field', 'transactions', 'lease_end',                    false, false, false, 'Lease end date. Lease.'),
  ('TXN','RENEWAL_TERMS',                '{{TXN.RENEWAL_TERMS}}',                'field', 'transactions', 'renewal_terms',                false, false, false, 'Lease renewal terms. Lease.'),
  ('TXN','PERMITTED_ACTIVITIES',         '{{TXN.PERMITTED_ACTIVITIES}}',         'field', 'transactions', 'permitted_activities',         false, false, false, 'Use terms: permitted activities. Lease.'),
  ('TXN','USE_RESTRICTIONS',             '{{TXN.USE_RESTRICTIONS}}',             'field', 'transactions', 'use_restrictions',             false, false, false, 'Use terms: restrictions. Lease.'),
  ('TXN','RESERVED_DAYS',                '{{TXN.RESERVED_DAYS}}',                'field', 'transactions', 'reserved_days',                false, false, false, 'Use terms: days reserved to the lessor. Lease.'),
  ('TXN','AUTHORIZED_USERS',             '{{TXN.AUTHORIZED_USERS}}',             'field', 'transactions', 'authorized_users',             false, false, false, 'Use terms: authorized riders/handlers. Lease.'),
  ('TXN','BOARDING_RESPONSIBILITY',      '{{TXN.BOARDING_RESPONSIBILITY}}',      'field', 'transactions', 'boarding_responsibility',      false, false, false, 'Care allocation: boarding. Lease.'),
  ('TXN','CARE_RESPONSIBILITY',          '{{TXN.CARE_RESPONSIBILITY}}',          'field', 'transactions', 'care_responsibility',          false, false, false, 'Care allocation: daily care. Lease.'),
  ('TXN','ROUTINE_VET_RESPONSIBILITY',   '{{TXN.ROUTINE_VET_RESPONSIBILITY}}',   'field', 'transactions', 'routine_vet_responsibility',   false, false, false, 'Veterinary allocation: routine care. Lease.'),
  ('TXN','EMERGENCY_VET_RESPONSIBILITY', '{{TXN.EMERGENCY_VET_RESPONSIBILITY}}', 'field', 'transactions', 'emergency_vet_responsibility', false, false, false, 'Veterinary allocation: emergency care. Lease.'),
  ('TXN','VET_AUTH_CONTACT',             '{{TXN.VET_AUTH_CONTACT}}',             'field', 'transactions', 'vet_auth_contact',             false, false, false, 'Veterinary allocation: authorization contact. Lease.'),
  ('TXN','FARRIER_RESPONSIBILITY',       '{{TXN.FARRIER_RESPONSIBILITY}}',       'field', 'transactions', 'farrier_responsibility',       false, false, false, 'Farrier allocation. Lease.'),
  ('TXN','TRAINING_TERMS',               '{{TXN.TRAINING_TERMS}}',               'field', 'transactions', 'training_terms',               false, false, false, 'Training provider and restrictions. Lease.'),
  ('TXN','INSURANCE_REQUIREMENTS',       '{{TXN.INSURANCE_REQUIREMENTS}}',       'field', 'transactions', 'insurance_requirements',       false, false, false, 'Insurance requirements. Lease.'),
  ('TXN','LESSOR_EQUIPMENT',             '{{TXN.LESSOR_EQUIPMENT}}',             'field', 'transactions', 'lessor_equipment',             false, false, false, 'Equipment provided by the lessor. Lease.'),
  ('TXN','LESSEE_EQUIPMENT',             '{{TXN.LESSEE_EQUIPMENT}}',             'field', 'transactions', 'lessee_equipment',             false, false, false, 'Equipment provided by the lessee. Lease.'),
  ('TXN','COMPETITION_TERMS',            '{{TXN.COMPETITION_TERMS}}',            'field', 'transactions', 'competition_terms',            false, false, false, 'Competition permissions. Lease.'),
  ('TXN','COMPETITION_EXPENSES',         '{{TXN.COMPETITION_EXPENSES}}',         'field', 'transactions', 'competition_expenses',         false, false, false, 'Competition cost allocation. Lease.'),
  ('TXN','RISK_ALLOCATION',              '{{TXN.RISK_ALLOCATION}}',              'field', 'transactions', 'risk_allocation',              false, false, false, 'Allocation of injury/illness/death/loss-of-use risk. Lease.'),
  ('TXN','TERMINATION_TERMS',            '{{TXN.TERMINATION_TERMS}}',            'field', 'transactions', 'termination_terms',            false, false, false, 'Lease termination notice terms. Lease.')
ON CONFLICT DO NOTHING;
