/* Generate supabase/migrations/20260812T2010_emailextract_seed.sql from
 * scripts/emailextract/bodies.mjs — the same module scripts/emailextract/diff.mjs
 * proves byte-identical. Generated rather than hand-written so the migration and
 * the proof can never disagree.
 *
 *   node scripts/emailextract/gen-seed.mjs
 */
import { writeFileSync } from 'node:fs';
import { TEMPLATES } from './bodies.mjs';

const OUT = 'supabase/migrations/20260812T2010_emailextract_seed.sql';
const TAG = '$emailextract$';

function q(s) {
  if (s == null) return 'NULL';
  if (String(s).includes(TAG)) throw new Error('dollar-quote tag collision');
  return `${TAG}${s}${TAG}`;
}

const rows = TEMPLATES.map((t) => {
  const cols = [
    q(t.key),
    q(t.title),
    q(t.description),
    q(t.category),
    q(t.subject),
    q(t.body),
    q(t.fromRule ?? 'tenant'),
    q(t.replyRule ?? 'none'),
    q(t.recipients),
    t.transactional === false ? 'false' : 'true',
  ];
  return `  (${cols.join(',\n   ')})`;
}).join(',\n\n');

const sql = `-- EMAILEXTRACT — seed the 19 extracted email templates (TASK-EMAILEXTRACT).
--
-- GENERATED by scripts/emailextract/gen-seed.mjs from scripts/emailextract/bodies.mjs.
-- Do not hand-edit: re-run the generator, or (once the Templates > Emails editor
-- exists) change the wording through the editor, which is the entire point of this
-- task. This file is the ONE-TIME lift out of TypeScript, not the ongoing home of
-- the words.
--
-- Every body here is proven byte-identical to what api/ produced on origin/main —
-- 220 checks in scripts/emailextract/diff.mjs, covering each optional branch of
-- each email (guardian vs signer, note vs no note, footer vs no footer, named vs
-- nameless recipient, single vs plural).
--
-- ON RE-RUN: content columns are NOT overwritten. An owner edit made through the
-- editor must survive a replay of this migration, so ON CONFLICT touches only the
-- documentation columns. Re-seeding wording is a deliberate act, not a side effect.

INSERT INTO public.email_templates
  (email_key, title, description, category, subject, body,
   from_address_rule, reply_to_rule, recipient_note, transactional)
VALUES
${rows}
ON CONFLICT (email_key) DO UPDATE SET
  title          = EXCLUDED.title,
  description    = EXCLUDED.description,
  category       = EXCLUDED.category,
  recipient_note = EXCLUDED.recipient_note;
`;

writeFileSync(OUT, sql);
console.log(`wrote ${OUT} — ${TEMPLATES.length} templates, ${sql.length} bytes`);
